quipucords/qpc

qpc/messages.py
qpc report summary was deprecated so we should not direct users to that command
=> Direct users to use deployments command instead of summary

qpc/messages.py, qpc/scan/add.py
Removed max concurrency default for: 
https://github.com/quipucords/quipucords/issues/1858
Tests: 
```
+ qpc scan add --name VScan --sources VSource
Scan "VScan" was added.
qpc
+ qpc scan list
[
{
"id": 1,
"name": "VScan",
"options": {
"max_concurrency": 25
},
"scan_type": "inspect",
"sources": [
{
"id": 1,
"name": "VSource",
"source_type": "vcenter"
}
]
}
]
```
=> Removed max_concurrency default.

tox.ini
pin pydocstyle due to the current issue https://gitlab.com/pycqa/flake8-docstrings/issues/36
=> Pin pydocstyle in tox.ini

docs/source/man.rst, qpc.spec, qpc/messages.py, qpc/server/login_host.py, qpc/server/tests_login_host.py
closes #145 
---
**How to test:**
```
(qpc) bash-3.2$ qpc server login -h
usage: qpc server login [-h] [--username USERNAME] [--password PASSWORD]
optional arguments:
-h, --help           show this help message and exit
--username USERNAME  The user name to log in to the server. If not provided,
user will be prompted.
--password PASSWORD  The password to log in to the server. If not provided,
user will be prompted.
(qpc) bash-3.2$ qpc server login
User name: admin
Password:
Login successful.
(qpc) bash-3.2$ qpc server logout
Logged out.
(qpc) bash-3.2$ qpc server login --username admin
Password:
Login successful.
(qpc) bash-3.2$ qpc server logout
Logged out.
(qpc) bash-3.2$ qpc server login --password qpcpassw0rd
User name: admin
Login successful.
(qpc) bash-3.2$ qpc server logout
Logged …
```
=> Added password arg to server login

docs/source/man.rst, qpc.spec, qpc/messages.py, qpc/report/deployments.py, qpc/report/details.py, qpc/report/download.py, qpc/report/tests_report_deployments.py, qpc/report/tests_report_details.py, qpc/report/tests_report_download.py, qpc/utils.py
Closes #152 
`qpc report details`, `qpc report deployments` and `qpc report download` now all have a `--mask` option.
=> Changes to add --mask flag to report download commands 

qpc/report/merge.py
Example of the problem here:
https://github.com/quipucords/qpc/runs/7438213333?check_suite_focus=true#step:5:242
if json_dir is not a list it will pick the first letter of the path, which would be the root dir (`/`).
=> Fix a bug on json_dir treatment

qpc/cli.py, qpc/insights/tests_insights_upload.py
Removal is neccessary to simplify things for the end user, who might confuse the upload and publish subcommands.
Code was not completely removed, in case we need it in the future.
=> Remove insights upload from cli commands

qpc/cred/conftest.py, qpc/cred/test_openshift_cred_add.py, qpc/cred/test_openshift_cred_edit.py, qpc/cred/utils.py, qpc/messages.py
Incorrect message requests the user to insert a password instead of a token.
This fix refers to [DISCOVERY-185]
=> Correct message for ocp cred token prompt

qpc/cred/edit.py, qpc/cred/test_openshift_cred_edit.py
Token, password and sshkey are mutually exclusive arguments and cli shouldn't allow user to select more than one of them simultaneously.
=> Add token to mutually exclusive group

qpc/cred/utils.py, qpc/insights/conftest.py, qpc/insights/login.py, qpc/insights/tests_insights_configure.py, qpc/insights/tests_insights_login.py, qpc/insights/tests_insights_publish.py, qpc/insights/utils.py, qpc/messages.py, qpc/test_utils.py, qpc/utils.py
- Test improvements on qpc insights test modules
- The user will be prompted for his password instead of pasting it directly in terminal.
This implements [DISCOVERY-200]
=> Feature/password prompt insights add_login

qpc/insights/publish.py, qpc/insights/tests_insights_publish.py
Return error message to user if report doesnt exist or if report is not in expected format.
This PR implements[ [DISCOVERY-213]](https://issues.redhat.com/browse/DISCOVERY-213)
=> fix(insights): return error if report doesnt exist

qpc/report/conftest.py, qpc/report/deployments.py, qpc/report/details.py, qpc/report/insights.py, qpc/report/tests_report_deployments.py, qpc/report/tests_report_details.py, qpc/report/tests_report_insights.py, qpc/utils.py
Output files won't be required for deployments and details 
reports, content will be written to stdout as default when the user
choose json file format.
For insights reports, the behavior will be the same except for a little detail, the --json flag won't be necessary, the json report will be directly written to the stdout. 
This implements [[DISCOVERY-184]](https://issues.redhat.com/browse/DISCOVERY-184)
=> CLI shouldn't force output file for json reports 

qpc/utils.py
#222 / 64bd49e7 attempted to unify logging, but had one unintended consequence - StreamHandler was added only to `qpc.utils` logger. That logger is imported by some other modules, like `qpc.request`, so things appeared to work as expected - calling `qpc -v` would display some debugging messages on terminal, and everything outside of `qpc` could be found in log file.
However, since mostly everything else is using `logging.getLogger(__name__)`, messages clearly meant to be displayed to user also ended up only in log file. Example:
```
$ qpc  cred edit  --name='this doesnt exist no really it doesnt' --password
$   # nothing was displayed
```
["Credential "%s" does not exist." should be displayed](https://github.com/quipucords/qpc/blob/master/qpc/cred/edit.py#L134), but since this logger is …
=> Display qpc error messages to user

qpc/cred/test_openshift_cred_add.py, qpc/utils.py
API calls should only appear when log verbosity >= 2.
=> fix: api calls should not appear with verbosity 1

qpc/request.py, qpc/test_request.py, qpc/test_utils.py
Any binaries received in response_json that can be converted to json will be stored, otherwise replaced by "encoded blob ignored"
=> fix: stop storing binary responses in qpc.log

qpc/source/__init__.py, qpc/source/add.py, qpc/source/edit.py
The fields in which this text is being used were not case insensitive in the past, therefore needed a more explicit description on accepted values. A recent refactor modified this behavior.
This implements [[DISCOVERY-206]](https://issues.redhat.com/browse/DISCOVERY-206)
=> fix: improve acceptable arg options text

Makefile, qpc/__init__.py, qpc/release.py
chore: Updating qpc cli and man page version to reflect the poetry package version
- poetry run qpc --version
- deploy/qpc man qpc
Both return the poetry -s version (currently 1.2.2) which is what gets tagged in github.com/quipucords/qpc.
=> chore: Updating qpc cli and man page version to reflect the poetry package version

poetry.lock, pyproject.toml
With distutils deprecation we need to use packaging, which is not part of standard lib.
=> Add packaging dependency

poetry.lock, pyproject.toml
chore: adding setuptools as a dependency
- Adding setuptools as a poetry dependency.
PyCharm would not open the qpc project off the bat without it.
=> chore: adding setuptools as a dependency

Dockerfile
feat: Support copying productized man pages
- we need to support targets other than dsc.1, so copying all generated *.1 files to the man1/ directory.
=> feat: Support copying productized man pages

Dockerfile, deploy/docker_run.sh, deploy/qpc
Make qpc image compatible with toolbox.
```bash
make build-container
toolbox create --image qpc
```
Either run from host shell or from inside toolbox container
`toolbox run --container qpc <qpc /man qpc>`
`toolbox enter qpc` and then run `qpc <command>` or `man qpc` .
=> feature: make qpc container compatible with toolbox

.github/workflows/build.yml
Forks don't have access to secrets and can't complete this step.
=> Skip upload container image step on PRs from forks

.github/workflows/build.yml
See https://github.com/quipucords/quipucords/pull/2412
This time PR is created from same repo. This is by mistake, but gives us a chance to confirm that image **will** be uploaded.
=> Skip upload container image step on PRs from forks... for real

qpc/cli.py, qpc/test_cli.py
Relates to JIRA: DISCOVERY-359 (https://issues.redhat.com/browse/DISCOVERY-359)
Followup to https://github.com/quipucords/qpc/pull/260 after a brief discussion in Slack.
Works same as before, just with a different argument:
```
❯ poetry run qpc --build-sha
2d510750503a33aa291429a4760382613d6a2515
❯ QPC_COMMIT=74205 poetry run qpc --build-sha
74205
```
=> refactor: rename `--version-git` arg to `--build-sha` to better indicate its purpose

poetry.lock, pyproject.toml
ruff should be labeled as a dev dependency (we don't need more rust dependencies than what we already have XD)
=> chore(deps): move ruff to dev dependencies group

.github/workflows/build.yml
This is implementing the same as https://github.com/quipucords/quipucords/pull/2419 but for this repo; see that PR for details.
Relates to JIRA: DISCOVERY-388
https://issues.redhat.com/browse/DISCOVERY-388
=> push to registry regardless of fork, use more variables

pyproject.toml
Relax the rules for pydocstyle checks. Allow having empty __init__ methods.
=> chore(lint): disable pydocstyle check for __init__ methods

docs/source/man.j2, docs/source/man.rst
I found these broken lines when looking at the actual man page. Broken output is quite ugly with unformatted junk like this throughout:
```
Configuring the server ~~~~~~~~~~~~~~~~~~~~~~
```
...
```
Listing and Showing Credentials ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Remember that RST is pretty strict about its syntax. The "underlines" for section headers should be the exact same length as the text above them. It's not as forgiving as many markdown flavors are.
=> fix: fix invalid rst syntax

Makefile, docs/jinja-render.py, docs/test_jina_render.py, poetry.lock, pyproject.toml, requirements-build.txt
Packages for `jinja-cli` and `jinja-cli2` are not available in our downstream build system. Our use case for rendering Jinja template content is very simple, though. So, I wrote this small script to use the `jinja2` library directly (which we _do_ have available downstream for both RHEL8 and RHEL9) to replace our single use of the `jinja` program, and I dropped `jinja-cli` from our Poetry environment and replaced it with just `jinja2`.
I deliberately made this a standalone script and _not_ part of the `qpc` package because we want to run this as a build step downstream, and we don't need to install all of qpc just to generate the man page.
=> replace jinja-cli with local python script

poetry.lock, pyproject.toml, requirements-build.txt
chore: Updating ruff to 0.1.3
- This helps eliminate the following warnings:
$ poetry run ruff
warning: Selection of nursery rule `PLC1901` without the `--preview` flag is deprecated.
warning: Selection of nursery rule `PLC1901` without the `--preview` flag is deprecated.
warning: Selection of nursery rule `PLC1901` without the `--preview` flag is deprecated.
=> Updating ruff to 0.1.3

Jenkinsfile
Add the same Jenkinsfile as we have in quipucords, so qpc PRs are covered by Camayoc.
This also requires a change in Jenkins configuration, there will be a PR in swatch-ci repo.
=> Add Jenkinsfile for internal CI

qpc/tests/scan/test_scan_add.py, qpc/tests/source/test_openshift_source_add.py, qpc/tests/source/test_source_add.py
A little unexpectedly, there were few tests in Camayoc that checked CLI input validation. They bail out before any requests are sent, so can be safely tested at the unit level.
=> test: port CLI tests from Camayoc

poetry.lock, qpc/cred/__init__.py, qpc/cred/clear.py, qpc/messages.py, qpc/tests/cred/test_cred_clear.py, qpc/utils.py
Also `make update-requirements` to stay on top of recent package updates since this repo is relatively inactive.
=> perf: optimize "cred clear --all" by using new bulk delete API

poetry.lock, qpc/messages.py, qpc/scan/__init__.py, qpc/scan/clear.py, qpc/source/__init__.py, qpc/source/clear.py, qpc/tests/cred/test_cred_clear.py, qpc/tests/mixins.py, qpc/tests/scan/test_scan_clear.py, qpc/tests/source/test_source_clear.py
…and also some refactoring cleanup along the way including:
* `docs: update test_cred_clear module docstring`
* `test: deduplicate similar clear all/bulk delete tests into a reusable mixin`
* `chore: make update-requirements`
This PR should also resolve https://github.com/quipucords/qpc/pull/318.
=> perf: optimize "source clear --all" and "scan clear --all" by using new bulk delete APIs

.coveragerc, qpc/tests/cred/test_cred_add.py, qpc/tests/cred/test_cred_clear.py, qpc/tests/scan/test_scan_add.py, qpc/tests/scan/test_scan_clear.py, qpc/tests/source/test_source_add.py, qpc/tests/source/test_source_clear.py
I recently discovered that our coverage metrics were ignoring our tests, and that means we were missing the fact that some test code was never being executed. That's bad because test code not being executed means that our assertions are wrong or the underlying code it's testing is wrong. Either way, it's masking bugs.
Upon closer inspection, yes, missing test coverage indicates that we have bugs in our tests _and_ their underlying code. What a mess! 😮‍💨 This PR only fixes _some_ of the many problems in existing tests, but it does leave the code in a better state than I found it. There is still much to be done to make these tests useful and healthy.
Unfortunately, in this investigation, I found some tests that, once fixed to assert what they were _probably_ intended to assert, revealed …
=> test: tests should not be excluded from coverage!

pyproject.toml, qpc.spec, qpc/utils.py
The latest refactor on merge and upload report apis require discovery 1.8.0 or greater.
Relates to JIRA: DISCOVERY-672
=> chore: bump version to 1.8.0

qpc/insights/publish.py, qpc/messages.py
I wanted to work on DISCOVERY-458 , but then I discovered that there's hardly anything to do. But since I was there already, I decided to clean up things a little.
f13d2ef8dec8fb6a9dfa27defc54a92046b39102 removes `filehandle.close()` call after context manager. File is closed by context manager on exit.
a94d8f26f45b5f4fb7695c30c8e06b2e81fd55e6 removes a bunch of variables from `messages.py`. These variables are no longer used - they generally belong to features that have since been removed (old insights upload, restart/pause, separate merge and upload), but some of them date back to when CLI and backend shared single repo - they were never really used in CLI.
=> Minor cleanup

qpc/cli.py
This changes the way argparse validates incomplete subparser (subcommand) inputs. By setting `required=true`, argparse correctly halts processing, displays a useful error message, and returns a non-zero exit code.
Old handling of incomplete commands:
```
$ qpc server
usage: qpc [-h] [--version] [-v] {server,cred,source,scan,report,insights} ...
positional arguments:
{server,cred,source,scan,report,insights}
options:
-h, --help            show this help message and exit
--version             show program's version number and exit
-v                    Verbose mode. Use up to -vvvv for more verbosity.
$ echo $?
0
```
Note that the old output simply dumps the top-level help message which does not actually help with the provided `server` subcommand, and it exits with `0` which wrongly …
=> feat: better output and exit code from incomplete commands

docs/_build/QPC_VAR_PROGRAM_NAME.1, docs/_build/man-qpc.rst, docs/_build/qpc.1, docs/source/man-template.rst, qpc/cred/__init__.py, qpc/cred/add.py, qpc/cred/edit.py, qpc/cred/utils.py, qpc/tests/cred/test_cred_add.py, qpc/tests/cred/test_cred_clear.py, qpc/tests/cred/test_cred_edit.py, qpc/tests/cred/test_cred_list.py, qpc/tests/cred/test_cred_show.py, qpc/tests/cred/test_openshift_cred_add.py, qpc/tests/cred/test_openshift_cred_edit.py, qpc/tests/cred/test_openshift_cred_list.py, qpc/tests/source/test_source_edit.py
See https://github.com/quipucords/quipucords/pull/2744 for details about the new API.
Relates to JIRA: DISCOVERY-797
=> feat: use new credentials v2 api

.github/workflows/test.yml, codecov.yml
This commit is basically a sibling/partner to https://github.com/quipucords/quipucords/pull/2824. As I stated there…
I _feel like_ qpc used to have non-default codecov configs somewhere, probably in codecov's web interface, and I _suspect_ those might have just disappeared some time ago when they upgraded their system (likely when they changed token use requirements).  🤷  Regardless, we should set our own config with the repo for complete visibility.
This config basically says:
* For the diff, require 80% coverage to pass the PR check.
* For the overall project, target the previous/parent commit's recorded coverage, but allow it to dip by 5% before it fails the PR check.
* The "range" value is purely aesthetic, IIUC. Files under 70% show as red, under 90% as yellow, and over 90% as green …
=> refactor: add codecov.yml config to override defaults

qpc/messages.py, qpc/report/insights.py, qpc/scan/__init__.py, qpc/scan/cancel.py, qpc/tests/report/test_report_insights.py, qpc/tests/scan/test_scan_cancel.py
All examples assume user is interacting with report that does not support insights report (so scan used sources of type {openshift, rhacs, ansible}).
Before the patch:
```
$ qpc -v report insights --report 2
Insights report 2 does not exist.
```
```
$ qpc -v report insights --scan-job 5
No Insights report available for scan job 5.
```
After this patch:
```
$ qpc -v report insights --report 2
Insights report 2 does not exist. Insights report can be generated only if at least one source type is network, satellite or vcenter.
```
```
$ qpc -v report insights --scan-job 5
No Insights report available for scan job 5. Insights report can be generated only if at least one source type is network, satellite or vcenter.
```
If user tries to download report by using non-existing report id or scan …
=> fix: Tell user when insights report can't be generated due to source types

conftest.py, qpc/cli.py, qpc/insights/configure.py, qpc/insights/publish.py, qpc/server/configure_host.py, qpc/tests/cred/conftest.py, qpc/tests/insights/conftest.py, qpc/tests/report/conftest.py, qpc/tests/source/conftest.py, qpc/tests/test_qpc_utils.py, qpc/tests/test_request.py, qpc/utils.py
This fixes DISCOVERY-815 .
Before this patch, when you run `dsc server config` for the first time ever, you get notification about config file not existing. That is triggered by `read_require_auth()` call. The easiest way is indenting this entire block - so when command is `server config`, we go straight to running a command. For anything else, we keep the current logic.
I've run all Camayoc cli tests using qpc with that patch and they passed.
=> fix: Don't warn about non-existing config file when creating it

Makefile
That command stopped working in December 2023 (4e2de281). We removed `Dockerfile`, but forgot about `make` target.
=> Remove `make build-container`

qpc.spec, qpc/release.py
I tested this by creating a build using a temporary additional commit containing the following patch:
```patch
--- a/qpc.spec
+++ b/qpc.spec
@@ -10,7 +10,7 @@
%global python3_pkgversion 3.12
%global __python3 /usr/bin/python3.12
%endif
-%global binname qpc
+%global binname potato
Name:           qpc
Summary:        command-line client interface for quipucords
```
I waited for the packit/copr to complete a build for RHEL9, installed that build on a RHEL9 VM, and confirmed that the new bin name worked and was used in the help text where previously `qpc` was incorrectly used downstream.
```
[brasmith@rhel9 ~]$ potato
usage: potato [-h] [--version] [-v] {server,cred,source,scan,report,insights} ...
positional arguments:
{server,cred,source,scan,report,insights}
options:
-h, --help …
```
=> fix: improve custom bin name handling for downstream builds

docs/_build/QPC_VAR_PROGRAM_NAME.1, docs/_build/man-qpc.rst, docs/_build/qpc.1, docs/source/man-template.rst, qpc/cred/add.py, qpc/cred/edit.py, qpc/cred/utils.py, qpc/messages.py, qpc/tests/cred/test_cred_add.py, qpc/tests/cred/test_cred_edit.py, qpc/tests/cred/test_openshift_cred_add.py
- Support the --sshkeyfile argument for allowing users to input the ssh key by filename.  Allow for - as filename to take stdin as it would behave today for --sshkey
- Drop support for the --sshkey argument.
Draft for now ...
to do's:
Solves: [DISCOVERY-811](https://issues.redhat.com/browse/DISCOVERY-811)
Requires: [camayoc/582](https://github.com/quipucords/camayoc/pull/582)
=> Add support for the --sshkeyfile parameter

pyproject.toml
Corresponds with https://github.com/quipucords/quipucords/pull/2977 update to use uv 0.7+.
=> build: update minimum uv from 0.6 to 0.7 (no max version)
