- CONTRIBUTING.rst
- README.rst
> Improve readme to reflect cli

- README.rst
- docs/source/insights_upload_configuration.rst
> Document how to install insights client and upload file (#10)

- qpc/report/deployments.py
- qpc/report/details.py
- qpc/report/tests_report_deployments.py
- qpc/report/tests_report_details.py
- qpc/report/tests_report_download.py
- qpc/utils.py
> Enhance tar.gz

- qpc/clicommand.py
- qpc/messages.py
- qpc/report/download.py
- qpc/report/tests_report_download.py
- qpc/utils.py
> Add version checking to CLI

- README.rst
- docs/source/man.rst
- qpc/messages.py
- qpc/server/configure_host.py
- qpc/server/tests_configure_host.py
> Changed default port to 9443 (#43)

- docs/source/man.rst
- insights_configuration.rst
- qpc.spec
- qpc/insights/__init__.py
- qpc/insights/tests_insights_upload.py
- qpc/insights/upload.py
- qpc/insights/utils.py
- qpc/messages.py
- qpc/report/insights.py
- qpc/report/tests_report_insights.py
> Update qpc insights upload commands to use new insights endpoint

- Makefile
- qpc/clicommand.py
- qpc/insights/tests_insights_upload.py
- qpc/insights/upload.py
- qpc/insights/utils.py
- qpc/messages.py
- qpc/report/download.py
- qpc/report/tests_deprecated_report_detail.py
- qpc/report/tests_deprecated_report_summary.py
- qpc/report/tests_report_deployments.py
- qpc/report/tests_report_details.py
- qpc/report/tests_report_download.py
- qpc/report/tests_report_insights.py
- qpc/request.py
- qpc/tests_qpc_utils.py
- qpc/tests_utilities.py
- qpc/utils.py
> Insights upload from local json

- docs/source/man.rst
I have added suggested changes to the manpage. Either they were grammatical or they were things I struggled to parse when I read them
> update to manpage.rst

- qpc/cli.py
- qpc/messages.py
- qpc/report/deployments.py
- qpc/report/details.py
- qpc/report/download.py
- qpc/report/insights.py
- qpc/report/tests_report_deployments.py
- qpc/report/tests_report_details.py
- qpc/report/tests_report_download.py
- qpc/report/tests_report_insights.py
- qpc/utils.py
> Add check for file extensions when downloading reports

- docs/source/man.rst
General man page edits:
- grammar/style edits
- some info improvements/additions in consultation with @abaiken @myersCody and @kholdaway 
Please review, thanks.
Closes #90
> 90: man page general edits

- Makefile
- docs/source/man.rst
- insights_configuration.rst
- qpc/insights/tests_insights_upload.py
- qpc/insights/tests_insights_utils.py
- qpc/insights/upload.py
- qpc/insights/utils.py
- qpc/messages.py
- qpc/report/insights.py
- qpc/report/tests_report_insights.py
> Updates required to handle new insights tar.gz format

- qpc/request.py
> Allow development version of the quipucords server

- qpc/cli.py
- qpc/messages.py
- qpc/request.py
> Make the connection error more clear. 

- qpc.spec
- qpc/release.py
-Update Python site packages
-Update Source0 to valid link
-Remove support for Python < 3.6
-Remove unneccessary conditionals for pandoc installation
-Fix wrong date on changelog, wrong day of the week
> Update qpc package version to 0.10.0

- qpc/insights/http.py
- qpc/insights/test_insights_http.py
Create class InsightsClient which will be responsible for handling
requests to C.RH.C.
This is part of the implementation of Discovery-131 feature.
> Add HTTP client for console.redhat.com

- qpc/cli.py
- qpc/insights/__init__.py
- qpc/insights/commands.py
- qpc/insights/publish.py
- qpc/insights/tests_insights_publish.py
- qpc/messages.py
- tox.ini
Create class InsightsPublishCommand which is responsible for publishing
the generated report to insights.
This is part of the implementation of DISCOVERY-131 feature.
> Add insights publish command

- qpc/insights/configure.py
- qpc/insights/tests_insights_configure.py
- qpc/insights/tests_insights_login.py
Add headers and translation symbols wherever missing
> Add headers and translation symbols wherever missing

- dev-requirements.txt
- qpc.spec
- qpc/insights/publish.py
- qpc/insights/tests_insights_publish.py
- qpc/messages.py
- qpc/release.py
- qpc/utils.py
- Validate insights report tarball
- Log ingress response
> [DISCOVERY-166] validate insights input file

- qpc/utils.py
> [DISCOVERY-169] - Make Log handlers more friendly to camayoc

- .github/workflows/rpm.yml
- qpc.spec
Also add a CI step checking RPM build
> Fix a bug in RPM build

- README.md
README instructions were outdated.
fix: DISCOVERY-223
> chore: Update README instructions

- qpc/cred/add.py
- qpc/cred/list.py
- qpc/cred/utils.py
- qpc/messages.py
- qpc/source/__init__.py
- qpc/source/add.py
- qpc/source/list.py
Add support to new "ansible" data source.
> DISCOVERY-43 - support for ansible automation controller

- Makefile
remove code related to the old insights integration.
> refactor: remove unused code

- docs/source/man.rst
Update man page to incorporate new features, functionality changes, and additions. Include Openshift and Ansible as credential and source options. Clarify that reports can be retrieved without requiring an output file. Provide comprehensive instructions for using "qpc insights" and its subcommands.
This feature implements [[DISCOVERY-211]](https://issues.redhat.com/browse/DISCOVERY-211)
> docs: update man page

- Dockerfile
- Makefile
- setup.py
Account for recent changes on directive `manpage` on the container image.
Relates to JIRA: DISCOVERY-310
> fix(manpage): build manpage on the container image

- qpc/report/merge.py
- qpc/report/test_report_merge.py
- further "pytestify" this test
- fix small errors
- improve the tests (now they actually test something)
- highlight some potential bugs that affect the current implementation.
> Improve test_merge_report

- conftest.py
- pyproject.toml
- qpc/cred/test_cred_add.py
- qpc/cred/test_cred_edit.py
- qpc/insights/publish.py
- qpc/insights/test_password_encryption.py
- qpc/insights/tests_insights_configure.py
- qpc/insights/tests_insights_publish.py
- qpc/report/merge.py
- qpc/report/test_report_deployments.py
- qpc/report/test_report_details.py
- qpc/report/test_report_download.py
- qpc/report/test_report_insights.py
- qpc/report/test_report_upload.py
- qpc/report/utils.py
- qpc/server/test_logout_host.py
- qpc/server/test_status.py
- qpc/source/test_source_add.py
- qpc/source/test_source_edit.py
- qpc/test_qpc_utils.py
- qpc/utils.py
prefer `pathlib` over `os.path`.
Before merging I'll squash all 5 commits into a single one.
> All things pathlib

- qpc/__init__.py
- setup.py
Fixing some issues that surfaced in the downstream build.
I strongly urge reevaluating the current logic in the near future and refactoring it to be more straightforward and robust.
> 1.3 fix build issues

- .github/workflows/test.yml
- pyproject.toml
- qpc/__init__.py
- qpc/test_request.py
- qpc/utils.py
- setup.py
Pulling recent 1.3-specific changes back to `main`.
```
git checkout release/1.3
git pull
git checkout -b 'merge-1.3-to-main'
git rebase origin/main
```
> Merge 1.3 to main

- qpc/messages.py
- qpc/report/deployments.py
- qpc/report/details.py
- qpc/report/download.py
- qpc/report/test_report_deployments.py
- qpc/report/test_report_details.py
- qpc/report/test_report_download.py
See also related change in quipucords: https://github.com/quipucords/quipucords/pull/2470
> refactor: drop support for masking report values

- README.md
- poetry.lock
- pyproject.toml
- qpc/__init__.py
- qpc/cred/commands.py
- qpc/insights/configure.py
- qpc/insights/exceptions.py
- qpc/insights/http.py
- qpc/release.py
- qpc/report/deployments.py
- qpc/scan/cancel.py
- qpc/tests/cred/conftest.py
- qpc/tests/cred/test_cred_list.py
- qpc/tests/cred/test_openshift_cred_add.py
- qpc/tests/cred/test_openshift_cred_edit.py
- qpc/tests/cred/test_openshift_cred_list.py
- qpc/tests/insights/test_insights_configure.py
- qpc/tests/insights/test_insights_http.py
- qpc/tests/insights/test_insights_utilities.py
- qpc/tests/source/conftest.py
- qpc/tests/source/test_openshift_source_add.py
- qpc/tests/source/test_openshift_source_edit.py
- qpc/tests/source/test_openshift_source_list.py
- qpc/tests/test_release.py
- qpc/translation.py
> chore: pin python~3.11 and pytest<8.0.0, update poetry.lock and README.md

- poetry.lock
- pyproject.toml
- qpc.spec
Also `make update-requirements` to update dev dependencies.
> build: update qpc version to 1.10.0

- pyproject.toml
- qpc.spec
- qpc/utils.py
- uv.lock
Relates to JIRA: DISCOVERY-925
> build: update qpc version to 1.13.1, minimum server version to 1.13.1
